
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "pry"
gem "activerecord"
gem "sinatra-activerecord"
gem "rake"
gem "sqlite3"
gem "require_all"

gem "tty-prompt", "~> 0.23.0"

gem "artii", "~> 2.1"

gem "ruby2d", "~> 0.9.5"

gem "tty-progressbar", "~> 0.18.1"
